# Generated by Django 4.2.1 on 2023-07-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
